//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nicenicenice
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishListed_DB
    {
        public string UserIdw { get; set; }
        public int ProductIdw { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
